### ISSUE TITLE
Issue About Finding `alfworld_game_files.json` File

### ISSUE THREAD

**Issue by consultantQ** [WeiminXiong/IPR#1]
Hello Team,
I'm working with the "construct_preference_monte_carlo_alfworld" script, but it cannot find the 'alfworld_game_files.json' file. 
I got the error below:
```
Traceback (most recent call last):
  File "/data/x/IPR/monte_carlo_sample_alfworld.py", line 477, in <module>
    sample_monte_carlo_response(args)
  File "/data/x/IPR/monte_carlo_sample_alfworld.py", line 200, in sample_monte_carlo_response
    all_game_files = json.load(open("alfworld_game_files.json"))
FileNotFoundError: [Errno 2] No such file or directory: 'alfworld_game_files.json'
```
How could I find or construct this file? Thank you!

**Comment by WeiminXiong** [comment]
Thanks for the feedback, I've uploaded the corresponding file.
